new comments

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -33,55 +33,55 @@ jobs:
       EKS_CLUSTER: vprofile-eks
 
     steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
+     # - name: Checkout source code
+     #   uses: actions/checkout@v4
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+     # - name: Configure AWS credentials
+     #   uses: aws-actions/configure-aws-credentials@v1
+      #  with:
+      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+       #   aws-region: ${{ env.AWS_REGION }}
 
-      - name: Setup terraform with specified version on the runner
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: "1.6.3"
+     # - name: Setup terraform with specified version on the runner
+       # uses: hashicorp/setup-terraform@v3
+      #  with:
+      #    terraform_version: "1.6.3"
 
-      - name: Terraform init
-        id: init
-        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"
+     # - name: Terraform init
+     #   id: init
+     #   run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"
 
-      - name: Terraform format
-        id: fmt
-        run: terraform fmt -check
+      #- name: Terraform format
+      #  id: fmt
+      #  run: terraform fmt -check
 
       - name: Terraform validate
         id: validate
         run: terraform validate
 
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input=false -out=planfile
-        continue-on-error: true 
+      #- name: Terraform plan
+      #  id: plan
+      #  run: terraform plan -no-color -input=false -out=planfile
+      #  continue-on-error: true 
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      #- name: Terraform plan status
+       # if: steps.plan.outcome == 'failure'
+      #  run: exit 1
 
-      - name: Terraform apply
-        id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+      #- name: Terraform apply
+        #id: apply
+      #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+       # run: terraform apply -auto-approve -input=false -parallelism=1 planfile
 
-      - name: Get Kube config file
-        id: getconfig
-        if: steps.apply.outcome == 'success'
-        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
+      #- name: Get Kube config file
+      #  id: getconfig
+      #  if: steps.apply.outcome == 'success'
+      #  run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
 
-      - name: Install Ingress controller
-        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
-        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+      #- name: Install Ingress controller
+      #  if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
+       # run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
 
       - name: Terraform destroy
         run: terraform destroy -auto-approve -input=false
